In [2]:
import numpy as np

In [3]:
x = np.array([[1,2,3],[4,5,6]])
y = np.ones((2,3))
print(x)
print(y)

[[1 2 3]
 [4 5 6]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [4]:
x.reshape(-1)

array([1, 2, 3, 4, 5, 6])

In [6]:
print(x)
x[:,1]

[[1 2 3]
 [4 5 6]]


array([2, 5])

In [9]:

[np.equal.outer(x[:, i], x[:, i]) for i in range(3)]



[array([[ True, False],
        [False,  True]]),
 array([[ True, False],
        [False,  True]]),
 array([[ True, False],
        [False,  True]])]

In [14]:
np.empty(16, np.int16).reshape((4,4))

array([[    0,     0,     1,     0],
       [    0,     0, 32760,     0],
       [ 1284,     0,     0,     0],
       [  768,     0,   554,     0]], dtype=int16)

In [17]:
a = np.random.randint(0,100,16).reshape((4,4))

In [18]:
a

array([[29, 60, 26, 42],
       [88, 55, 35, 35],
       [75, 27, 71, 42],
       [13, 19, 80, 64]])

In [21]:
[np.equal.outer(a[:, i], a[:, i]) for i in range(a.shape[1])]

[array([[ True, False, False, False],
        [False,  True, False, False],
        [False, False,  True, False],
        [False, False, False,  True]]),
 array([[ True, False, False, False],
        [False,  True, False, False],
        [False, False,  True, False],
        [False, False, False,  True]]),
 array([[ True, False, False, False],
        [False,  True, False, False],
        [False, False,  True, False],
        [False, False, False,  True]]),
 array([[ True, False,  True, False],
        [False,  True, False, False],
        [ True, False,  True, False],
        [False, False, False,  True]])]

In [19]:
sum(np.equal.outer(a[:, i], a[:, i]) for i in range(a.shape[1]))

array([[4, 0, 1, 0],
       [0, 4, 0, 0],
       [1, 0, 4, 0],
       [0, 0, 0, 4]])

In [ ]:
[np.equal.outer(x[:, i], x[:, i]) for i in range(3)]

In [20]:
sum(np.equal.outer(x[:, i], x[:, i]) for i in range(3))

array([[3, 0],
       [0, 3]])

In [25]:
sum(np.equal.outer(x[:, i], x[:, i]) for i in range(x.shape[1]))

array([[3, 0],
       [0, 3]])