In [2]:
import numpy as np

In [3]:
x = np.array([[1,2,3],[1,0,2],[1,3,3]])
print(x)
nTrees = x.shape[1]

[[1 2 3]
 [1 0 2]
 [1 3 3]]


In [4]:
equality_matrices = [np.equal.outer(x[:,i], x[:,i]) for i in range(nTrees)]

for i in range(len(equality_matrices)):
    print(equality_matrices[i])

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True False False]
 [False  True False]
 [False False  True]]
[[ True False  True]
 [False  True False]
 [ True False  True]]


In [5]:
sum(equality_matrices)

array([[3, 1, 2],
       [1, 3, 1],
       [2, 1, 3]])

In [6]:
x.reshape(-1)

array([1, 2, 3, 1, 0, 2, 1, 3, 3])

In [8]:
x.reshape(-1).reshape(-1,1)

array([[1],
       [2],
       [3],
       [1],
       [0],
       [2],
       [1],
       [3],
       [3]])